@startuml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Context.puml

Person(Volunteer, "Volunteer", "Homeless shelter volunteer")
Person(ShelterStaff, "Shelter Staff", "Homeless shelter staff")
Boundary(b1, "Our System"){
System(schedulingApp, "Volunteer Scheduling Application", "Web Application")
}
System_Ext(getHelp, "GetHelp Platform")

Rel(Volunteer, schedulingApp, "Uses", "Web Browswer")
Rel(ShelterStaff, schedulingApp, "Uses", "Web Browser")
Rel(schedulingApp, getHelp, "Requests data", "HTTPS")
@enduml
